### ISSUE TITLE
Create a private chat group - Telegram

### ISSUE THREAD

**Issue by s4n-cz** [dissect-ctu/dissect.eu#10]

**Comment by s4n-cz** [comment]
Group created, now make all people use it :slightly_smiling_face: 

 - Web: https://telegram.org/
 - Android: https://play.google.com/store/apps/details?id=org.telegram.messenger
 - Flatpak: https://flathub.org/apps/details/org.telegram.desktop

After registering, ask @acsjakub to add you to the group.

**Comment by acsjakub** [comment]
Done and dusted
